### ISSUE TITLE
Can't build - bad :documentation in defpackage?

### ISSUE THREAD

**Issue by quicklisp** [mmaul/clml#15]
SBCL complains about https://github.com/mmaul/clml/blob/master/hjs/src/package.lisp#L211 - it seems to have invalid syntax. I'm not sure what the :documentation clause is even meant to demonstrate. It looks like incomplete output or something.

**Comment by quicklisp** [comment]
http://report.quicklisp.org/2017-01-16/failure-report/clml.html#clml has a log.

**Comment by mmaul** [comment]
The #+include inside the documentation string is an org-mode directive which pulls in sample code in the generated documentation. However the real problem was un-escaped quotes in documentation strings. Which apparently was not an issue is in sbcl versions at some point less than or equal to 1.3.14. The issues is now resolved.
