### ISSUE TITLE
quick load fails

### ISSUE THREAD

**Issue by wh1tew0lf** [mmaul/clml#8]
Hello,

I entered ```CL-USER> (ql:quickload :clml :verbose t)```
And got this:
```
To load "clml":
  Load 1 ASDF system:
    clml
; Loading "clml"
STYLE-WARNING: redefining CLML.NEAREST-SEARCH-ENVIRONMENT::CALL-WITH-ENVIRONMENT in DEFUN
STYLE-WARNING: redefining CLML.NEAREST-SEARCH-ENVIRONMENT::CALL-WITH-ENVIRONMENT in DEFUN
.
STYLE-WARNING: redefining CLML.BLAS-ENVIRONMENT::CALL-WITH-ENVIRONMENT in DEFUN
STYLE-WARNING: redefining CLML.STATISTICS.RAND-ENVIRONMENT::CALL-WITH-ENVIRONMENT in DEFUN
..
WARNING:
   compiling #<STATIC-FILE "alexandria" "LICENCE"> completed without its input file #P"/usr/share/common-lisp/source/alexandria/LICENCE"
WARNING:
   loading #<STATIC-FILE "alexandria" "LICENCE"> completed without its input file #P"/usr/share/common-lisp/source/alexandria/LICENCE"

; compiling file "/home/wh1/quicklisp/local-projects/clml/lapack/src/dgesvd.lisp" (written 13 SEP 2015 08:00:24 PM):
; compiling (IN-PACKAGE :CLML.LAPACK)
; compiling (LET* (# #) ...)...............................................
.........
```
And no actions after this. I was waited some time, but there were no changes.
How to get more information and where is problem?
I use linux mint 17, run it from emacs24 + slime.

**Comment by mmaul** [comment]
You need to start sbcl with a larger heap sizeof 2560K or larger
  sbcl –dynamic-space-size 2560
However after clml.lapack is compiled you should not need to use this switch. This is noted in the Requirements section of the README, though I think I could have presented it better. The source of the problem is dgesvd.lisp which is about 10K lines of lisp generated by f2cl from the fortran dgesvd. I'd like to sort it out I've just had other priorities.

**Comment by wh1tew0lf** [comment]
Sorry, I skipped it when was reading. Thanks, now all compiled and work. I used 4096M of heap.

**Comment by guicho271828** [comment]
how about signalling error on sbcl when (< (dynamic-space-size) 2560) using :before method for asdf?

**Comment by mmaul** [comment]
That is brilliant; done.
